__author__ = 'hmt1501'
__github__ = 'https://github.com/hmt1501'
__email__ = 'hmt1501@users.noreply.github.com'

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Station:
    code: str          # đài code / URL slug / file name, e.g. 'xshcm'
    name: str          # display name, e.g. 'Xổ số TPHCM'
    region: str        # region page slug: 'xsmn' (South) | 'xsmt' (Central)
    weekdays: frozenset[int] = field(default_factory=frozenset)  # 0=Mon .. 6=Sun


# Full list of Central (xsmt) and Northern-excluded provinces.
# Generated by scanning https://xoso.com.vn/{region}-{date}.html over a full week.
# `weekdays` is only used to skip dates a station certainly does not draw when
# back-filling; the region page itself is the source of truth for which đài drew.
STATIONS: list[Station] = [
    # ----- Miền Nam (South) - 21 đài -----
    Station('xshcm', 'Xổ số TPHCM', 'xsmn', frozenset({0, 5})),
    Station('xsdt', 'Xổ số Đồng Tháp', 'xsmn', frozenset({0})),
    Station('xscm', 'Xổ số Cà Mau', 'xsmn', frozenset({0})),
    Station('xsbtr', 'Xổ số Bến Tre', 'xsmn', frozenset({1})),
    Station('xsvt', 'Xổ số Vũng Tàu', 'xsmn', frozenset({1})),
    Station('xsbl', 'Xổ số Bạc Liêu', 'xsmn', frozenset({1})),
    Station('xsdn', 'Xổ số Đồng Nai', 'xsmn', frozenset({2})),
    Station('xsct', 'Xổ số Cần Thơ', 'xsmn', frozenset({2})),
    Station('xsst', 'Xổ số Sóc Trăng', 'xsmn', frozenset({2})),
    Station('xstn', 'Xổ số Tây Ninh', 'xsmn', frozenset({3})),
    Station('xsag', 'Xổ số An Giang', 'xsmn', frozenset({3})),
    Station('xsbth', 'Xổ số Bình Thuận', 'xsmn', frozenset({3})),
    Station('xsvl', 'Xổ số Vĩnh Long', 'xsmn', frozenset({4})),
    Station('xsbd', 'Xổ số Bình Dương', 'xsmn', frozenset({4})),
    Station('xstv', 'Xổ số Trà Vinh', 'xsmn', frozenset({4})),
    Station('xsla', 'Xổ số Long An', 'xsmn', frozenset({5})),
    Station('xsbp', 'Xổ số Bình Phước', 'xsmn', frozenset({5})),
    Station('xshg', 'Xổ số Hậu Giang', 'xsmn', frozenset({5})),
    Station('xstg', 'Xổ số Tiền Giang', 'xsmn', frozenset({6})),
    Station('xskg', 'Xổ số Kiên Giang', 'xsmn', frozenset({6})),
    Station('xsdl', 'Xổ số Đà Lạt', 'xsmn', frozenset({6})),
    # ----- Miền Trung (Central) - 14 đài -----
    Station('xspy', 'Xổ số Phú Yên', 'xsmt', frozenset({0})),
    Station('xstth', 'Xổ số Huế', 'xsmt', frozenset({0, 6})),
    Station('xsdlk', 'Xổ số Đắk Lắk', 'xsmt', frozenset({1})),
    Station('xsqna', 'Xổ số Quảng Nam', 'xsmt', frozenset({1})),
    Station('xsdna', 'Xổ số Đà Nẵng', 'xsmt', frozenset({2, 5})),
    Station('xskh', 'Xổ số Khánh Hòa', 'xsmt', frozenset({2, 6})),
    Station('xsbdi', 'Xổ số Bình Định', 'xsmt', frozenset({3})),
    Station('xsqt', 'Xổ số Quảng Trị', 'xsmt', frozenset({3})),
    Station('xsqb', 'Xổ số Quảng Bình', 'xsmt', frozenset({3})),
    Station('xsgl', 'Xổ số Gia Lai', 'xsmt', frozenset({4})),
    Station('xsnt', 'Xổ số Ninh Thuận', 'xsmt', frozenset({4})),
    Station('xsqng', 'Xổ số Quảng Ngãi', 'xsmt', frozenset({5})),
    Station('xsdno', 'Xổ số Đắk Nông', 'xsmt', frozenset({5})),
    Station('xskt', 'Xổ số Kon Tum', 'xsmt', frozenset({6})),
]

STATION_BY_CODE: dict[str, Station] = {s.code: s for s in STATIONS}

REGIONS: tuple[str, ...] = ('xsmn', 'xsmt')


def stations_of(region: str) -> list[Station]:
    return [s for s in STATIONS if s.region == region]
